version: "3.8"
services:
  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env.local
    restart: on-failure
    volumes:
      - ./minio:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  postgresWeb:
    image: postgres
    restart: always
    volumes:
      - ./webPgData:/var/lib/postgresql/data
    env_file:
      - .env.local
    ports:
      - "6000:5432"
  pgAdmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env.local
    ports:
      - "7000:7000"

  elastic:
    image: elasticsearch:8.13.4
    restart: always
    ports:
      - "9200:9200"
    env_file:
      - .env.local
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
      - action.destructive_requires_name=false
    volumes:
      - ./elasticData:/usr/share/elasticsearch/data
    networks:
      - thesis
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: kibana:8.13.4
    restart: always
    ports:
      - "5601:5601"
    env_file:
      - .env.local
    networks:
      - thesis
    depends_on:
      - elastic

networks:
  thesis:
    driver: bridge
